# Generated by Django 2.1.7 on 2019-04-09 12:22

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20190327_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='client_id',
            field=models.CharField(blank=True, help_text='Client ID extracted from Auth header', max_length=100, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='notificatie',
            name='forwarded_msg',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
