# Generated by Django 2.2.2 on 2019-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0008_auto_20190409_1422")]

    operations = [
        migrations.AddField(
            model_name="notificatieresponse",
            name="response_status_int",
            field=models.IntegerField(null=True),
        )
    ]
