# Generated by Django 2.2.2 on 2019-06-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("datamodel", "0011_remove_notificatieresponse_response_status")]

    operations = [
        migrations.RenameField(
            model_name="notificatieresponse",
            old_name="response_status_int",
            new_name="response_status",
        )
    ]
