# Generated by Django 3.2.13 on 2022-04-28 13:03

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0012_auto_20190605_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kanaal",
            name="filters",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Lijst van mogelijke filter kenmerken van een KANAAL. Deze filter kenmerken kunnen worden gebruikt bij het aanmaken van een ABONNEMENT.",
                size=None,
                verbose_name="filters",
            ),
        ),
        migrations.AlterField(
            model_name="kanaal",
            name="naam",
            field=models.CharField(
                help_text='Naam van het KANAAL (ook wel "Exchange" genoemd) dat de bron vertegenwoordigd.',
                max_length=50,
                unique=True,
                verbose_name="Naam",
            ),
        ),
        migrations.AlterField(
            model_name="notificatie",
            name="forwarded_msg",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
