# Generated by Django 3.2.13 on 2022-05-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0014_auto_20220503_1450"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="sink_credentials",
            new_name="sink_credential",
        ),
    ]
