# Generated by Django 3.2.13 on 2022-05-24 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0014_auto_20220519_0906"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="datamodel.domain",
                verbose_name="Domain",
            ),
        ),
    ]
