# Generated by Django 3.2.13 on 2022-05-25 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0015_alter_subscription_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Aanmaakdatum"
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Laatst bewerkt"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Aanmaakdatum"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Laatst bewerkt"),
        ),
    ]
