# Generated by Django 3.2.13 on 2022-05-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0016_auto_20220525_1415"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ("created_on",),
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.AlterField(
            model_name="subscription",
            name="protocol",
            field=models.CharField(
                choices=[("HTTP", "HTTP")],
                help_text="Identificatie van het aflever protocol.",
                max_length=255,
            ),
        ),
    ]
