# Generated by Django 3.2.13 on 2022-05-31 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0018_alter_subscription_sink"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="filter_attributes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                help_text="Filtering op EVENTs op basis van opgegeven attributen",
                null=True,
                size=None,
            ),
        ),
    ]
