# Generated by Django 3.2.13 on 2022-05-31 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0019_domain_filter_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="filter_attributes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                default=list,
                help_text="Filtering op EVENTs op basis van opgegeven attributen",
                size=None,
            ),
        ),
    ]
