# Generated by Django 3.2.13 on 2022-05-31 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0020_alter_domain_filter_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={
                "ordering": ("-created_on", "name"),
                "verbose_name": "domain",
                "verbose_name_plural": "domains",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("-created_on",)},
        ),
        migrations.AlterModelOptions(
            name="eventresponse",
            options={"ordering": ("-created_on", "-last_updated")},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ("-created_on",),
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Aanmaakdatum"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Laatst bewerkt"),
        ),
        migrations.AddField(
            model_name="eventresponse",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Aanmaakdatum"
            ),
        ),
        migrations.AddField(
            model_name="eventresponse",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Laatst bewerkt"),
        ),
    ]
