# Generated by Django 3.2.13 on 2022-05-31 13:46

from django.db import migrations, models

import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0022_auto_20220531_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="filter_attributes",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Filtering op EVENTs op basis van opgegeven attributen",
                size=None,
            ),
        ),
    ]
