# Generated by Django 3.2.13 on 2022-06-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0025_subscription_subscriber_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="source",
            field=models.CharField(
                blank=True, help_text="Bron van dit abonnement.", max_length=255
            ),
        ),
    ]
