# Generated by Django 3.2.13 on 2022-06-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0026_alter_subscription_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Bron van dit abonnement.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscriber_reference",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Referentie subscription",
            ),
        ),
    ]
