# Generated by Django 3.2.13 on 2022-06-08 14:21

import uuid

from django.db import migrations


def create_uuids(apps, schema_editor):
    Domain = apps.get_model("datamodel", "domain")
    for domain in Domain.objects.all():
        domain.uuid = uuid.uuid4()
        domain.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0028_alter_subscription_types"),
    ]

    operations = [
        migrations.RunPython(create_uuids, reverse_code=migrations.RunPython.noop)
    ]
