# Generated by Django 3.2.13 on 2022-06-08 14:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0029_auto_20220608_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique resource identifier (UUID4)",
                unique=True,
            ),
        ),
    ]
