# Generated by Django 3.2.13 on 2022-06-14 12:13

import uuid

from django.db import migrations, models

import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("datamodel", "0032_auto_20220614_1208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="documentation_link",
            field=models.URLField(
                blank=True,
                help_text="Link to human readable information about the domain and its notifications.",
                verbose_name="Documentatie link",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="filter_attributes",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Filter attributes offered by the domain.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(
                help_text="Name of the domain.",
                max_length=255,
                unique=True,
                verbose_name="Naam",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="UUID of the domain.", unique=True
            ),
        ),
    ]
