# Generated by Django 2.1.7 on 2019-03-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanaal',
            name='abonnement',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='kanaals',
            field=models.ManyToManyField(related_name='abonnementen', to='datamodel.Kanaal'),
        ),
        migrations.AddField(
            model_name='filter',
            name='abonnement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Kanaal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kanaal',
            name='documentatie_link',
            field=models.URLField(default=1, help_text='Url of subscriber API to which NC will post messages', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanaal',
            name='naam',
            field=models.CharField(help_text='name of the channel/exchange', max_length=50, unique=True),
        ),
    ]
