# Generated by Django 2.1.7 on 2019-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20190313_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanaal',
            name='documentatie_link',
            field=models.URLField(help_text='Url of subscriber API to which NC will post messages', null=True),
        ),
    ]
