# Generated by Django 2.1.7 on 2019-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_auto_20190313_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='kanaals',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='kanalen',
            field=models.ManyToManyField(to='datamodel.Kanaal'),
        ),
    ]
