# Generated by Django 2.1.7 on 2019-03-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20190313_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='abonnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Abonnement'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='kanaal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Kanaal'),
        ),
    ]
