# Generated by Django 2.1.7 on 2019-03-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_notificatie_notificatieresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificatieresponse',
            old_name='response',
            new_name='response_status',
        ),
    ]
