# Generated by Django 2.1.7 on 2019-03-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_auto_20190313_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='kanaal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='datamodel.Kanaal'),
        ),
        migrations.AlterField(
            model_name='kanaal',
            name='naam',
            field=models.CharField(help_text='name of the channel/exchange', max_length=50),
        ),
    ]
