# Generated by Django 2.1.7 on 2019-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0006_auto_20190314_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanaal',
            name='naam',
            field=models.CharField(help_text='name of the channel/exchange', max_length=50, unique=True),
        ),
    ]
